export const newWatchProviders = [
    'Disney Plus',
    'Amazon Video',
    'Paramount Plus',
    'Apple TV',
    'AMC on Demand',
    'Now TV'
];
export const languageMap = {
    "af": "Afrikaans",
    "sq": "Albanian",
    "ar-dz": "Arabic (Algeria)",
    "ar-bh": "Arabic (Bahrain)",
    "ar-eg": "Arabic (Egypt)",
    "ar-iq": "Arabic (Iraq)",
    "ar-jo": "Arabic (Jordan)",
    "ar-kw": "Arabic (Kuwait)",
    "ar-lb": "Arabic (Lebanon)",
    "ar-ly": "Arabic (Libya)",
    "ar-ma": "Arabic (Morocco)",
    "ar-om": "Arabic (Oman)",
    "ar-qa": "Arabic (Qatar)",
    "ar-sa": "Arabic (Saudi Arabia)",
    "ar-sy": "Arabic (Syria)",
    "ar-tn": "Arabic (Tunisia)",
    "ar-ae": "Arabic (U.A.E.)",
    "ar-ye": "Arabic (Yemen)",
    "eu": "Basque",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "zh-hk": "Chinese (Hong Kong)",
    "zh-cn": "Chinese (PRC)",
    "zh-sg": "Chinese (Singapore)",
    "zh-tw": "Chinese (Taiwan)",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl-be": "Dutch (Belgium)",
    "nl": "Dutch (Standard)",
    "en": "English",
    "en-au": "English (Australia)",
    "en-bz": "English (Belize)",
    "en-ca": "English (Canada)",
    "en-ie": "English (Ireland)",
    "en-jm": "English (Jamaica)",
    "en-nz": "English (New Zealand)",
    "en-za": "English (South Africa)",
    "en-tt": "English (Trinidad)",
    "en-gb": "English (United Kingdom)",
    "en-us": "English (United States)",
    "et": "Estonian",
    "fo": "Faeroese",
    "fa": "Farsi",
    "fi": "Finnish",
    "fr-be": "French (Belgium)",
    "fr-ca": "French (Canada)",
    "fr-lu": "French (Luxembourg)",
    "fr": "French (Standard)",
    "fr-ch": "French (Switzerland)",
    "gd": "Gaelic (Scotland)",
    "de-at": "German (Austria)",
    "de-li": "German (Liechtenstein)",
    "de-lu": "German (Luxembourg)",
    "de": "German (Standard)",
    "de-ch": "German (Switzerland)",
    "el": "Greek",
    "he": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian (Standard)",
    "it-ch": "Italian (Switzerland)",
    "ja": "Japanese",
    "ko": "Korean",
    "ku": "Kurdish",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "mk": "Macedonian (FYROM)",
    "ml": "Malayalam",
    "ms": "Malaysian",
    "mt": "Maltese",
    "no": "Norwegian",
    "nb": "Norwegian (Bokmål)",
    "nn": "Norwegian (Nynorsk)",
    "pl": "Polish",
    "pt-br": "Portuguese (Brazil)",
    "pt": "Portuguese (Portugal)",
    "pa": "Punjabi",
    "rm": "Rhaeto-Romanic",
    "ro": "Romanian",
    "ro-md": "Romanian (Republic of Moldova)",
    "ru": "Russian",
    "ru-md": "Russian (Republic of Moldova)",
    "sr": "Serbian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sb": "Sorbian",
    "es-ar": "Spanish (Argentina)",
    "es-bo": "Spanish (Bolivia)",
    "es-cl": "Spanish (Chile)",
    "es-co": "Spanish (Colombia)",
    "es-cr": "Spanish (Costa Rica)",
    "es-do": "Spanish (Dominican Republic)",
    "es-ec": "Spanish (Ecuador)",
    "es-sv": "Spanish (El Salvador)",
    "es-gt": "Spanish (Guatemala)",
    "es-hn": "Spanish (Honduras)",
    "es-mx": "Spanish (Mexico)",
    "es-ni": "Spanish (Nicaragua)",
    "es-pa": "Spanish (Panama)",
    "es-py": "Spanish (Paraguay)",
    "es-pe": "Spanish (Peru)",
    "es-pr": "Spanish (Puerto Rico)",
    "es": "Spanish (Spain)",
    "es-uy": "Spanish (Uruguay)",
    "es-ve": "Spanish (Venezuela)",
    "sv": "Swedish",
    "sv-fi": "Swedish (Finland)",
    "th": "Thai",
    "ts": "Tsonga",
    "tn": "Tswana",
    "tr": "Turkish",
    "ua": "Ukrainian",
    "ur": "Urdu",
    "ve": "Venda",
    "vi": "Vietnamese",
    "cy": "Welsh",
    "xh": "Xhosa",
    "ji": "Yiddish",
    "zu": "Zulu",
};

export const gbCertifications = ["U", "PG", "12", "12A", "15", "18", "R18"];

export const genreOptions = [
    "Action",
    "Adventure",
    "Animation",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "History",
    "Horror",
    "Music",
    "Mystery",
    "Romance",
    "Science Fiction",
    "TV Movie",
    "Thriller",
    "War",
    "Western",
];

export const releaseTypeOptions = [
    "Premiere",
    "Theatrical (limited)",
    "Theatrical",
    "Digital",
    "Physical",
    "TV",
];

export const allFilters = [
    { label: "Certification", key: "certification", type: "certification" },
    { label: "Include Adult Content", key: "includeAdult", type: "boolean" },
    { label: "Include Videos", key: "includeVideo", type: "boolean" },
    { label: "Language", key: "language", type: "string" },
    { label: "Page", key: "page", type: "int" },
    { label: "Release Year", key: "primaryReleaseYear", type: "date" },
    { label: "Release Date From", key: "releaseDate.gte", type: "date" },
    { label: "Release Date To", key: "releaseDate.lte", type: "date" },
    { label: "Region", key: "region", type: "string" },
    {
        label: "Sort By",
        key: "sortBy",
        type: "select",
        options: [
            { label: "Popularity", value: "POPULARITY_DESC" },
            { label: "Release Date", value: "RELEASE_DATE_DESC" },
            { label: "Vote Average", value: "VOTE_AVERAGE_DESC" },
        ]
    },
    { label: "Min Vote Average", key: "voteAverage.gte", type: "float" },
    { label: "Max Vote Average", key: "voteAverage.lte", type: "float" },
    { label: "Min Vote Count", key: "voteCount.gte", type: "int" },
    { label: "Max Vote Count", key: "voteCount.lte", type: "int" },
    { label: "Watch Region", key: "watchRegion", type: "string" },
    { label: "Cast", key: "withCast", type: "string" },
    { label: "Companies", key: "withCompanies", type: "string" },
    { label: "Exclude Companies", key: "withoutCompanies", type: "string" },
    { label: "Crew", key: "withCrew", type: "string" },
    { label: "Genres", key: "withGenres", type: "string", options: genreOptions },
    { label: "Exclude Genres", key: "withoutGenres", type: "string", options: genreOptions },
    { label: "Exclude Keywords", key: "withoutKeywords", type: "string" },
    { label: "Origin Country", key: "withOriginCountry", type: "string" },
    { label: "Original Language", key: "withOriginalLanguage", type: "string" },
    { label: "People", key: "with_people", type: "string" },
    { label: "Release Type", key: "withReleaseType", type: "string", options: releaseTypeOptions },
    { label: "Min Runtime (min)", key: "withRuntime.gte", type: "int" },
    { label: "Max Runtime (min)", key: "withRuntime.lte", type: "int" },
    { label: "Monetization Types", key: "withWatchMonetizationTypes", type: "string" },
    { label: "Watch Providers", key: "withWatchProviders", type: "string", options: [...newWatchProviders] },
    { label: "Exclude Watch Providers", key: "withoutWatchProviders", type: "string", options: [...newWatchProviders] },
];