export const newWatchProviders = [
    'Disney Plus',
    'Amazon Video',
    'Paramount Plus',
    'Apple TV',
    'AMC on Demand',
    'Now TV'
];
export const languageMap = {
    "af": "Afrikaans",
    "sq": "Albanian",
    "ar-dz": "Arabic (Algeria)",
    "ar-bh": "Arabic (Bahrain)",
    "ar-eg": "Arabic (Egypt)",
    "ar-iq": "Arabic (Iraq)",
    "ar-jo": "Arabic (Jordan)",
    "ar-kw": "Arabic (Kuwait)",
    "ar-lb": "Arabic (Lebanon)",
    "ar-ly": "Arabic (Libya)",
    "ar-ma": "Arabic (Morocco)",
    "ar-om": "Arabic (Oman)",
    "ar-qa": "Arabic (Qatar)",
    "ar-sa": "Arabic (Saudi Arabia)",
    "ar-sy": "Arabic (Syria)",
    "ar-tn": "Arabic (Tunisia)",
    "ar-ae": "Arabic (U.A.E.)",
    "ar-ye": "Arabic (Yemen)",
    "eu": "Basque",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "zh-hk": "Chinese (Hong Kong)",
    "zh-cn": "Chinese (PRC)",
    "zh-sg": "Chinese (Singapore)",
    "zh-tw": "Chinese (Taiwan)",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl-be": "Dutch (Belgium)",
    "nl": "Dutch (Standard)",
    "en": "English",
    "en-au": "English (Australia)",
    "en-bz": "English (Belize)",
    "en-ca": "English (Canada)",
    "en-ie": "English (Ireland)",
    "en-jm": "English (Jamaica)",
    "en-nz": "English (New Zealand)",
    "en-za": "English (South Africa)",
    "en-tt": "English (Trinidad)",
    "en-gb": "English (United Kingdom)",
    "en-us": "English (United States)",
    "et": "Estonian",
    "fo": "Faeroese",
    "fa": "Farsi",
    "fi": "Finnish",
    "fr-be": "French (Belgium)",
    "fr-ca": "French (Canada)",
    "fr-lu": "French (Luxembourg)",
    "fr": "French (Standard)",
    "fr-ch": "French (Switzerland)",
    "gd": "Gaelic (Scotland)",
    "de-at": "German (Austria)",
    "de-li": "German (Liechtenstein)",
    "de-lu": "German (Luxembourg)",
    "de": "German (Standard)",
    "de-ch": "German (Switzerland)",
    "el": "Greek",
    "he": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian (Standard)",
    "it-ch": "Italian (Switzerland)",
    "ja": "Japanese",
    "ko": "Korean",
    "ku": "Kurdish",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "mk": "Macedonian (FYROM)",
    "ml": "Malayalam",
    "ms": "Malaysian",
    "mt": "Maltese",
    "no": "Norwegian",
    "nb": "Norwegian (Bokmål)",
    "nn": "Norwegian (Nynorsk)",
    "pl": "Polish",
    "pt-br": "Portuguese (Brazil)",
    "pt": "Portuguese (Portugal)",
    "pa": "Punjabi",
    "rm": "Rhaeto-Romanic",
    "ro": "Romanian",
    "ro-md": "Romanian (Republic of Moldova)",
    "ru": "Russian",
    "ru-md": "Russian (Republic of Moldova)",
    "sr": "Serbian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sb": "Sorbian",
    "es-ar": "Spanish (Argentina)",
    "es-bo": "Spanish (Bolivia)",
    "es-cl": "Spanish (Chile)",
    "es-co": "Spanish (Colombia)",
    "es-cr": "Spanish (Costa Rica)",
    "es-do": "Spanish (Dominican Republic)",
    "es-ec": "Spanish (Ecuador)",
    "es-sv": "Spanish (El Salvador)",
    "es-gt": "Spanish (Guatemala)",
    "es-hn": "Spanish (Honduras)",
    "es-mx": "Spanish (Mexico)",
    "es-ni": "Spanish (Nicaragua)",
    "es-pa": "Spanish (Panama)",
    "es-py": "Spanish (Paraguay)",
    "es-pe": "Spanish (Peru)",
    "es-pr": "Spanish (Puerto Rico)",
    "es": "Spanish (Spain)",
    "es-uy": "Spanish (Uruguay)",
    "es-ve": "Spanish (Venezuela)",
    "sv": "Swedish",
    "sv-fi": "Swedish (Finland)",
    "th": "Thai",
    "ts": "Tsonga",
    "tn": "Tswana",
    "tr": "Turkish",
    "ua": "Ukrainian",
    "ur": "Urdu",
    "ve": "Venda",
    "vi": "Vietnamese",
    "cy": "Welsh",
    "xh": "Xhosa",
    "ji": "Yiddish",
    "zu": "Zulu",
};

export const gbCertifications = ["U", "PG", "12", "12A", "15", "18", "R18"];

export const allFilters = [
    { label: "Certification", key: "certification", type: "certification" },
    { label: "Include Adult Content", key: "include_adult", type: "boolean" },
    { label: "Include Videos", key: "include_video", type: "boolean" },
    { label: "Language", key: "language", type: "string" },
    { label: "Page", key: "page", type: "int" },
    { label: "Release Year", key: "primary_release_year", type: "date" },
    { label: "Release Date From", key: "release_date.gte", type: "date" },
    { label: "Release Date To", key: "release_date.lte", type: "date" },
    { label: "Region", key: "region", type: "string" },
    { label: "Sort By", key: "sort_by", type: "select", options: ["popularity", "release date", "vote average"] },
    { label: "Min Vote Average", key: "vote_average.gte", type: "float" },
    { label: "Max Vote Average", key: "vote_average.lte", type: "float" },
    { label: "Min Vote Count", key: "vote_count.gte", type: "int" },
    { label: "Max Vote Count", key: "vote_count.lte", type: "int" },
    { label: "Watch Region", key: "watch_region", type: "string" },
    { label: "With Cast", key: "with_cast", type: "string" },
    { label: "With Companies", key: "with_companies", type: "string" },
    { label: "With Crew", key: "with_crew", type: "string" },
    { label: "With Genres", key: "with_genres", type: "string" },
    { label: "With Keywords", key: "with_keywords", type: "string" },
    { label: "With Origin Country", key: "with_origin_country", type: "string" },
    { label: "With Original Language", key: "with_original_language", type: "string" },
    { label: "With People", key: "with_people", type: "string" },
    { label: "With Release Type", key: "with_release_type", type: "string" },
    { label: "Min Runtime (min)", key: "with_runtime.gte", type: "int" },
    { label: "Max Runtime (min)", key: "with_runtime.lte", type: "int" },
    { label: "Monetization Types", key: "with_watch_monetization_types", type: "string" },
    { label: "Watch Providers", key: "with_watch_providers", type: "string", options: [...newWatchProviders] },
    { label: "Exclude Companies", key: "without_companies", type: "string" },
    { label: "Exclude Genres", key: "without_genres", type: "string" },
    { label: "Exclude Keywords", key: "without_keywords", type: "string" },
    { label: "Exclude Watch Providers", key: "without_watch_providers", type: "string" },
    // { label: "Year", key: "year", type: "int" },
];